trigger: none    
steps:
      - pwsh: |
        displayName: Export RSG details to CSV
        script: |
            $resourceGroupList = Get-AzResourceGroup | select-Object -Property ResourceGroupName,Location,ResourceId,ProvisioningState,@{N='Enviroment (Tag)'; E={$_.Tags.Enviroment}} ,@{N='Ownership (Tag)'; E={$_.Tags.Ownership}} 
            $resourceGroupList | export-csv test11.csv -NoTypeInformation