trigger: none
steps: 
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 86f78685-6d6b-46f9-8c67-b80970f7bc45
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show