trigger: none    
displayName: Export RSG details to CSV
steps:
      - pwsh: |
            $resourceGroupList = Get-AzResourceGroup | select-Object -Property ResourceGroupName,Location,ResourceId,ProvisioningState,@{N='Enviroment (Tag)'; E={$_.Tags.Enviroment}} ,@{N='Ownership (Tag)'; E={$_.Tags.Ownership}} 
            $resourceGroupList | export-csv test11.csv -NoTypeInformation
            Write-Host -ForegroundColor Magenta "Export to CSV done"
      - script: echo "Export Completed"   